---
title: Jay's Blog
baseurl: "/"
permalink: "/:title/"
description: Personal blog and portfolio of work I've done.
layout_style: overflow
palette: violet
header:
  title: Jay
  tagline: CS Major
  profile_img: "/images/Jemma_Com.gif"
  background: dark
  has_nav: true
  nav_links:
  - label: Home
    url: "/"
    type: link
  - label: Blog
    url: "/blog/"
    type: link
  - label: About
    url: "/about/"
    type: link
  has_social: true
footer:
  content: "&copy;Jemverse All rights reserved."
  links: []
sass:
  indentWidth: 4
  style: nested
  precision: 10
plugins:
- jekyll-menus
exclude:
- Gemfile
- Gemfile.lock
- node_modules
- vendor/bundle/
- vendor/cache/
- vendor/gems/
- vendor/ruby/
- ssg-build.sh
- LICENSE.md
- README.md
- netlify.toml
- stackbit-build.sh
- stackbit-pull.js
collections:
  posts:
    permalink: "/posts/:title/"
