title: Stackbit Fresh Theme
baseurl: /
permalink: '/:title/'
description: Personal blogging theme for Stackbit
layout_style: overflow
palette: blue
header:
  title: Stackbit Fresh
  tagline: Header Tagline
  profile_img: images/avatar.png
  background: dark
  has_nav: true
  nav_links:
    - label: Home
      url: /
      type: link
    - label: Blog
      url: /blog/
      type: link
    - label: Style Guide
      url: /style-guide/
      type: link
    - label: About
      url: /about/
      type: link
    - label: Contact
      url: /contact/
      type: link
  has_social: true
footer:
  content: '&copy; All rights reserved.'
  links:
    - label: Made with Stackbit.
      url: 'https://www.stackbit.com'
      type: link
      new_window: true
sass:
  indentWidth: 4
  style: nested
  precision: 10
plugins:
  - jekyll-menus
exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
  - ssg-build.sh
  - LICENSE.md
  - README.md
  - netlify.toml
  - stackbit-build.sh
  - stackbit-pull.js
collections:
  posts:
    permalink: '/posts/:title/'
