---
label: Action
hide_body: true
is_partial: true
display_field: label
fields:
  - type: text
    name: label
    label: Label
    config:
      required: true
  - type: text
    name: url
    label: URL
    config:
      required: true
  - type: select
    name: type
    label: Type
    default: link
    config:
      required: true
      source:
        type: custom
      options:
        - link
        - button
  - type: boolean
    name: new_window
    label: Open in new tab/window
    default: false
